### ISSUE TITLE
incorrect punctuation

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/aldous-huxley_crome-yellow#2]
https://github.com/standardebooks/aldous-huxley_crome-yellow/blob/49aee7096b3ae5c8f2d8643b8908f73529dcde40/src/epub/text/chapter-6.xhtml#L77-L82

These quotations within quotations begin with a left-double-quote and then a right-single-quote rather than two lefts.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
