### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/aldous-huxley_crome-yellow#3]
"back to frantic" should be "back to front"

https://github.com/standardebooks/aldous-huxley_crome-yellow/blob/cc08e0cb0d6ec6b3312c3ce7ec28dcc443a258f8/src/epub/text/chapter-8.xhtml#L24

https://books.google.com/books/content?id=bA-j9fLGI_wC&pg=PA76&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2FQ8Wi5opfyBZDS_KaVirMr7iZAw&ci=160%2C94%2C753%2C607&edge=0

**Comment by acabal** [comment]
Thanks, this should be fixed now!
